import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const mouseMemoirs = localFont({
  src: "../public/fonts/MouseMemoirs-Regular.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mouseMemoirs.className} h-screen min-h-[667px]`}>
        {children}
      </body>
    </html>
  );
}
